# Generated by Django 5.2.8 on 2025-11-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Arquivo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='arquivos/', verbose_name='Arquivo')),
                ('categoria', models.CharField(choices=[('trabalho', 'Trabalho'), ('projeto', 'Projeto'), ('pesquisa', 'Pesquisa'), ('outro', 'Outro')], default='trabalho', max_length=20)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
            },
        ),
    ]
