# Generated by Django 5.2.6 on 2025-10-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do usuario')),
                ('email', models.CharField(max_length=100, verbose_name='Email do usuario')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha do usuario')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função do usuario')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
